Repository Couch-Coders/6th-camp_us-be, pull requests merged in 2022-03, with the labels that each got.

#77 Feature/post delete
  src/main/java/couch/camping/controller/comment/CommentController.java
  src/main/java/couch/camping/controller/post/PostController.java
  src/main/java/couch/camping/domain/comment/repository/CommentCustomRepository.java
  src/main/java/couch/camping/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/couch/camping/domain/comment/service/CommentService.java
  src/main/java/couch/camping/domain/post/service/PostService.java
Labels: enhancement

#86 REFACTOR: 댓글 조회 쿼리 회원과 페치 조인 후 조회
  src/main/java/couch/camping/controller/comment/dto/response/CommentRetrieveResponseDto.java
  src/main/java/couch/camping/controller/post/dto/response/PostRetrieveResponseDto.java
  src/main/java/couch/camping/domain/comment/repository/CommentCustomRepository.java
  src/main/java/couch/camping/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/couch/camping/domain/comment/service/CommentService.java
  src/main/java/couch/camping/domain/post/repository/PostCustomRepository.java
  src/main/java/couch/camping/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/couch/camping/domain/post/service/PostService.java
Labels: refactor

#85 REFACTOR: 게시글 조회 쿼리 회원과 페치 조인 후 조회
  src/main/java/couch/camping/controller/post/dto/response/PostRetrieveResponseDto.java
  src/main/java/couch/camping/domain/post/repository/PostCustomRepository.java
  src/main/java/couch/camping/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/couch/camping/domain/post/service/PostService.java
Labels: refactor

#88 REFACTOR: 게시글 도메인에 의존적인 댓글 컨틀롤러 분리 및 querydsl 빌드
  build/generated/querydsl/couch/camping/domain/comment/entity/QComment.java
  build/generated/querydsl/couch/camping/domain/post/entity/QPost.java
  src/main/java/couch/camping/controller/comment/CommentController.java
  src/main/java/couch/camping/controller/post/PostCommentController.java
  src/main/java/couch/camping/controller/post/PostController.java
  src/main/java/couch/camping/domain/comment/service/CommentService.java
  src/main/java/couch/camping/domain/comment/service/CommentServiceImpl.java
  src/main/java/couch/camping/domain/comment/service/CommentServiceLocalImpl.java
  src/main/java/couch/camping/domain/post/service/PostService.java
  src/main/java/couch/camping/domain/post/service/PostServiceImpl.java
  src/main/java/couch/camping/domain/post/service/PostServiceLocalImpl.java
Labels: refactor

#101 FIX: 게시글 삭제 시 403 에러 해결
  build.gradle
  src/main/java/couch/camping/controller/post/dto/request/PostEditRequestDto.java
  src/main/java/couch/camping/controller/post/dto/request/PostWriteRequestDto.java
  src/main/java/couch/camping/controller/post/dto/response/PostEditResponseDto.java
  src/main/java/couch/camping/controller/post/dto/response/PostRetrieveResponseDto.java
  src/main/java/couch/camping/controller/post/dto/response/PostWriteResponseDto.java
  src/main/java/couch/camping/domain/post/entity/Post.java
  src/main/java/couch/camping/domain/post/service/PostServiceImpl.java
  src/main/java/couch/camping/domain/post/service/PostServiceLocalImpl.java
  src/test/java/couch/camping/common/BaseControllerTest.java
  src/test/java/couch/camping/controller/member/MemberControllerTest.java
  src/test/resources/application.yml
Labels: bug, refactor

#102 Develop
  build.gradle
  src/main/java/couch/camping/controller/post/dto/request/PostEditRequestDto.java
  src/main/java/couch/camping/controller/post/dto/request/PostWriteRequestDto.java
  src/main/java/couch/camping/controller/post/dto/response/PostEditResponseDto.java
  src/main/java/couch/camping/controller/post/dto/response/PostRetrieveResponseDto.java
  src/main/java/couch/camping/controller/post/dto/response/PostWriteResponseDto.java
  src/main/java/couch/camping/domain/post/entity/Post.java
  src/main/java/couch/camping/domain/post/service/PostServiceImpl.java
  src/main/java/couch/camping/domain/post/service/PostServiceLocalImpl.java
  src/test/java/couch/camping/common/BaseControllerTest.java
  src/test/java/couch/camping/controller/member/MemberControllerTest.java
  src/test/resources/application.yml
Labels: bug, refactor, test

#107 FIX: 게시글의 모든 댓글 조회 404 Error
  build/classes/java/main/couch/camping/domain/comment/service/CommentServiceImpl.class
  src/main/java/couch/camping/config/JasyptConfig.java
  src/main/java/couch/camping/controller/member/MemberCommentController.java
  src/main/java/couch/camping/controller/member/dto/response/MemberCommentsResponseDto.java
Labels: bug

#108 Develop
  build/classes/java/main/couch/camping/domain/comment/service/CommentServiceImpl.class
  src/main/java/couch/camping/config/JasyptConfig.java
  src/main/java/couch/camping/controller/member/MemberCommentController.java
  src/main/java/couch/camping/controller/member/dto/response/MemberCommentsResponseDto.java
Labels: develop->master

#109 FIX: 게시글의 모든 댓글 조회 404 Error(re)
  src/main/java/couch/camping/domain/comment/service/CommentServiceImpl.java
Labels: bug, refactor

#110 Develop
  src/main/java/couch/camping/domain/comment/service/CommentServiceImpl.java
Labels: develop->master

#111 REFACTOR: 게시글, 댓글과 관련된 알림 기능 추가 개발
  build/generated/querydsl/couch/camping/domain/notification/entity/QNotification.java
  src/main/java/couch/camping/controller/member/MemberNotificationController.java
  src/main/java/couch/camping/controller/member/dto/response/MemberNotificationResponseDto.java
  src/main/java/couch/camping/controller/member/dto/response/NotificationCommentRetrieveResponseDto.java
  src/main/java/couch/camping/controller/member/dto/response/NotificationCommentWriteRetrieveResponseDto.java
  src/main/java/couch/camping/controller/member/dto/response/NotificationPostRetrieveResponseDto.java
  src/main/java/couch/camping/controller/member/dto/response/NotificationReviewRetrieveResponseDto.java
  src/main/java/couch/camping/domain/comment/service/CommentServiceImpl.java
  src/main/java/couch/camping/domain/comment/service/CommentServiceLocalImpl.java
  src/main/java/couch/camping/domain/notification/entity/Notification.java
  src/main/java/couch/camping/domain/notification/repository/NotificationCustomRepository.java
  src/main/java/couch/camping/domain/notification/repository/NotificationCustomRepositoryImpl.java
  src/main/java/couch/camping/domain/notification/service/NotificationService.java
  src/main/java/couch/camping/domain/post/service/PostServiceImpl.java
  src/main/java/couch/camping/domain/post/service/PostServiceLocalImpl.java
  src/main/resources/application-local.yml
  src/test/java/couch/camping/controller/member/MemberControllerTest.java
Labels: enhancement, refactor

#112 Develop
  build/generated/querydsl/couch/camping/domain/notification/entity/QNotification.java
  src/main/java/couch/camping/controller/member/MemberNotificationController.java
  src/main/java/couch/camping/controller/member/dto/response/MemberNotificationResponseDto.java
  src/main/java/couch/camping/controller/member/dto/response/NotificationCommentRetrieveResponseDto.java
  src/main/java/couch/camping/controller/member/dto/response/NotificationCommentWriteRetrieveResponseDto.java
  src/main/java/couch/camping/controller/member/dto/response/NotificationPostRetrieveResponseDto.java
  src/main/java/couch/camping/controller/member/dto/response/NotificationReviewRetrieveResponseDto.java
  src/main/java/couch/camping/domain/comment/service/CommentServiceImpl.java
  src/main/java/couch/camping/domain/comment/service/CommentServiceLocalImpl.java
  src/main/java/couch/camping/domain/notification/entity/Notification.java
  src/main/java/couch/camping/domain/notification/repository/NotificationCustomRepository.java
  src/main/java/couch/camping/domain/notification/repository/NotificationCustomRepositoryImpl.java
  src/main/java/couch/camping/domain/notification/service/NotificationService.java
  src/main/java/couch/camping/domain/post/service/PostServiceImpl.java
  src/main/java/couch/camping/domain/post/service/PostServiceLocalImpl.java
  src/main/resources/application-local.yml
  src/test/java/couch/camping/controller/member/MemberControllerTest.java
Labels: develop->master

#114 REFACTOR: 게시글 댓글 전체 조회 API 페이징 처리 에러 수정
  src/main/java/couch/camping/controller/post/PostCommentController.java
  src/main/java/couch/camping/controller/post/PostController.java
  src/main/java/couch/camping/domain/comment/repository/CommentCustomRepositoryImpl.java
Labels: bug, refactor

#115 Develop
  src/main/java/couch/camping/controller/post/PostCommentController.java
  src/main/java/couch/camping/controller/post/PostController.java
  src/main/java/couch/camping/domain/comment/repository/CommentCustomRepositoryImpl.java
Labels: develop->master

#119 REFACTOR: 알림 전체 조회 API 응답 DTO 수정
  build/generated/querydsl/couch/camping/domain/comment/entity/QComment.java
  build/generated/querydsl/couch/camping/domain/post/entity/QPost.java
  src/main/java/couch/camping/controller/member/dto/response/NotificationCommentRetrieveResponseDto.java
  src/main/java/couch/camping/controller/member/dto/response/NotificationCommentWriteRetrieveResponseDto.java
  src/main/java/couch/camping/controller/member/dto/response/NotificationPostRetrieveResponseDto.java
  src/main/java/couch/camping/domain/comment/entity/Comment.java
  src/main/java/couch/camping/domain/comment/service/CommentServiceImpl.java
  src/main/java/couch/camping/domain/comment/service/CommentServiceLocalImpl.java
  src/main/java/couch/camping/domain/post/entity/Post.java
  src/main/java/couch/camping/domain/post/service/PostServiceImpl.java
  src/main/java/couch/camping/domain/post/service/PostServiceLocalImpl.java
  src/test/java/couch/camping/common/BaseControllerTest.java
  src/test/java/couch/camping/controller/member/MemberControllerTest.java
  src/test/resources/application-test.yml
Labels: refactor

#120 Develop
  build/generated/querydsl/couch/camping/domain/comment/entity/QComment.java
  build/generated/querydsl/couch/camping/domain/post/entity/QPost.java
  src/main/java/couch/camping/controller/member/dto/response/NotificationCommentRetrieveResponseDto.java
  src/main/java/couch/camping/controller/member/dto/response/NotificationCommentWriteRetrieveResponseDto.java
  src/main/java/couch/camping/controller/member/dto/response/NotificationPostRetrieveResponseDto.java
  src/main/java/couch/camping/domain/comment/entity/Comment.java
  src/main/java/couch/camping/domain/comment/service/CommentServiceImpl.java
  src/main/java/couch/camping/domain/comment/service/CommentServiceLocalImpl.java
  src/main/java/couch/camping/domain/post/entity/Post.java
  src/main/java/couch/camping/domain/post/service/PostServiceImpl.java
  src/main/java/couch/camping/domain/post/service/PostServiceLocalImpl.java
  src/test/java/couch/camping/common/BaseControllerTest.java
  src/test/java/couch/camping/controller/member/MemberControllerTest.java
  src/test/resources/application-test.yml
Labels: develop->master

#122 FEAT: 내가 쓴 댓글 조회 개발
  build.gradle
  build/classes/java/main/couch/camping/config/JasyptConfig.class
  build/classes/java/main/couch/camping/controller/member/MemberCommentController.class
  build/classes/java/main/couch/camping/controller/member/MemberNotificationController.class
  build/classes/java/main/couch/camping/controller/member/dto/response/MemberCommentsResponseDto$MemberCommentsResponseDtoBuilder.class
  build/classes/java/main/couch/camping/controller/member/dto/response/MemberCommentsResponseDto.class
  build/classes/java/main/couch/camping/controller/member/dto/response/MemberNotificationResponseDto$MemberNotificationResponseDtoBuilder.class
  build/classes/java/main/couch/camping/controller/member/dto/response/MemberNotificationResponseDto.class
  build/classes/java/main/couch/camping/controller/member/dto/response/NotificationCommentRetrieveResponseDto.class
  build/classes/java/main/couch/camping/controller/member/dto/response/NotificationCommentWriteRetrieveResponseDto.class
  build/classes/java/main/couch/camping/controller/member/dto/response/NotificationPostRetrieveResponseDto.class
  build/classes/java/main/couch/camping/controller/member/dto/response/NotificationRetrieveResponseDto$NotificationRetrieveResponseDtoBuilder.class
  build/classes/java/main/couch/camping/controller/member/dto/response/NotificationRetrieveResponseDto.class
  build/classes/java/main/couch/camping/controller/member/dto/response/NotificationReviewRetrieveResponseDto.class
  build/classes/java/main/couch/camping/controller/post/PostCommentController.class
  build/classes/java/main/couch/camping/controller/post/PostController.class
  build/classes/java/main/couch/camping/domain/comment/entity/Comment$CommentBuilder.class
  build/classes/java/main/couch/camping/domain/comment/entity/Comment.class
  build/classes/java/main/couch/camping/domain/comment/entity/QComment.class
  build/classes/java/main/couch/camping/domain/comment/repository/CommentCustomRepository.class
  build/classes/java/main/couch/camping/domain/comment/repository/CommentCustomRepositoryImpl.class
  build/classes/java/main/couch/camping/domain/comment/service/CommentService.class
  build/classes/java/main/couch/camping/domain/comment/service/CommentServiceImpl.class
  build/classes/java/main/couch/camping/domain/comment/service/CommentServiceLocalImpl.class
  build/classes/java/main/couch/camping/domain/notification/entity/Notification$NotificationBuilder.class
  build/classes/java/main/couch/camping/domain/notification/entity/Notification.class
  build/classes/java/main/couch/camping/domain/notification/entity/QNotification.class
  build/classes/java/main/couch/camping/domain/notification/repository/NotificationCustomRepository.class
  build/classes/java/main/couch/camping/domain/notification/repository/NotificationCustomRepositoryImpl.class
  build/classes/java/main/couch/camping/domain/notification/service/NotificationService.class
  build/classes/java/main/couch/camping/domain/post/entity/Post$PostBuilder.class
  build/classes/java/main/couch/camping/domain/post/entity/Post.class
  build/classes/java/main/couch/camping/domain/post/entity/QPost.class
  build/classes/java/main/couch/camping/domain/post/service/PostServiceImpl.class
  build/classes/java/main/couch/camping/domain/post/service/PostServiceLocalImpl.class
  build/classes/java/test/couch/camping/common/BaseControllerTest.class
  build/classes/java/test/couch/camping/controller/member/MemberControllerTest.class
  build/resources/main/application-local.yml
  build/resources/main/application.yml
  build/resources/test/application-test.yml
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
  src/main/java/couch/camping/config/JasyptConfig.java
  src/main/java/couch/camping/controller/comment/CommentController.java
  src/main/java/couch/camping/controller/member/MemberCommentController.java
  src/main/java/couch/camping/controller/member/dto/response/MemberCommentsResponseDto.java
  src/main/java/couch/camping/controller/post/PostCommentController.java
  src/main/java/couch/camping/domain/comment/repository/CommentCustomRepository.java
  src/main/java/couch/camping/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/couch/camping/domain/comment/service/CommentService.java
  src/main/java/couch/camping/domain/comment/service/CommentServiceImpl.java
  src/main/java/couch/camping/domain/comment/service/CommentServiceLocalImpl.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: enhancement

#128 회원이 작성한 게시글 및 댓글 조회
  build/classes/java/main/couch/camping/controller/member/dto/response/MemberCommentsResponseDto$MemberCommentsResponseDtoBuilder.class
  build/classes/java/main/couch/camping/controller/member/dto/response/MemberCommentsResponseDto.class
  build/classes/java/main/couch/camping/controller/member/dto/response/MemberPostResponseDto.class
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/couch/camping/controller/member/dto/response/MemberCommentsResponseDto.java
  src/main/java/couch/camping/controller/member/dto/response/MemberPostResponseDto.java
Labels: enhancement, refactor

#129 Develop
  build/classes/java/main/couch/camping/controller/member/dto/response/MemberCommentsResponseDto$MemberCommentsResponseDtoBuilder.class
  build/classes/java/main/couch/camping/controller/member/dto/response/MemberCommentsResponseDto.class
  build/classes/java/main/couch/camping/controller/member/dto/response/MemberPostResponseDto.class
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/couch/camping/controller/member/dto/response/MemberCommentsResponseDto.java
  src/main/java/couch/camping/controller/member/dto/response/MemberPostResponseDto.java
Labels: master<-develop

#131 Develop
  src/main/java/couch/camping/controller/member/dto/response/MemberRegisterResponseDto.java
  src/main/java/couch/camping/controller/post/PostController.java
  src/main/java/couch/camping/controller/post/dto/response/PostWriteResponseDto.java
  src/main/java/couch/camping/domain/member/service/MemberService.java
  src/main/java/couch/camping/domain/post/service/PostService.java
  src/main/java/couch/camping/domain/post/service/PostServiceImpl.java
  src/main/java/couch/camping/domain/post/service/PostServiceLocalImpl.java
  src/main/resources/application-local.yml
  src/test/java/couch/camping/domain/member/service/MemberServiceTest.java
  src/test/java/couch/camping/domain/post/service/PostServiceLocalImplTest.java
Labels: master<-develop

#135 REFACTOR: 게시글, 댓글 삭제를 위한 각 엔티티에 알림과 일대다 연관관계 추가
  src/main/java/couch/camping/controller/post/dto/response/PostEditResponseDto.java
  src/main/java/couch/camping/domain/comment/entity/Comment.java
  src/main/java/couch/camping/domain/post/entity/Post.java
  src/test/java/couch/camping/domain/post/service/PostServiceLocalImplTest.java
Labels: bug, refactor

#134 FIX: 내가 작성한 게시글에서 이미지URL과 comment개수가 반환되지 않던 버그 수정
  build/classes/java/main/couch/camping/controller/member/dto/response/MemberPostResponseDto.class
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/couch/camping/controller/member/dto/response/MemberPostResponseDto.java
Labels: bug

#136 Develop
  build/classes/java/main/couch/camping/controller/member/dto/response/MemberPostResponseDto.class
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/couch/camping/controller/member/dto/response/MemberPostResponseDto.java
  src/main/java/couch/camping/controller/post/dto/response/PostEditResponseDto.java
  src/main/java/couch/camping/domain/comment/entity/Comment.java
  src/main/java/couch/camping/domain/post/entity/Post.java
  src/test/java/couch/camping/domain/post/service/PostServiceLocalImplTest.java
Labels: master<-develop

#138 REFACTOR: 마이페이지에 좋아요한 캠핑장, 나의 게시글, 나의 댓글 개수 추가
  src/main/java/couch/camping/controller/member/MemberController.java
  src/main/java/couch/camping/controller/member/MemberPostController.java
  src/main/java/couch/camping/controller/member/dto/response/MemberRetrieveResponseDto.java
  src/main/java/couch/camping/domain/camplike/repository/CampLikeCustomRepository.java
  src/main/java/couch/camping/domain/camplike/repository/CampLikeCustomRepositoryImpl.java
  src/main/java/couch/camping/domain/comment/repository/CommentCustomRepository.java
  src/main/java/couch/camping/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/couch/camping/domain/comment/service/CommentService.java
  src/main/java/couch/camping/domain/comment/service/CommentServiceImpl.java
  src/main/java/couch/camping/domain/comment/service/CommentServiceLocalImpl.java
  src/main/java/couch/camping/domain/post/entity/Post.java
  src/main/java/couch/camping/domain/post/repository/PostCustomRepository.java
  src/main/java/couch/camping/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/couch/camping/domain/post/service/PostService.java
  src/main/java/couch/camping/domain/post/service/PostServiceImpl.java
  src/main/java/couch/camping/domain/post/service/PostServiceLocalImpl.java
  src/test/java/couch/camping/domain/post/service/PostServiceLocalImplTest.java
Labels: refactor

#139 Develop
  src/main/java/couch/camping/controller/member/MemberController.java
  src/main/java/couch/camping/controller/member/MemberPostController.java
  src/main/java/couch/camping/controller/member/dto/response/MemberRetrieveResponseDto.java
  src/main/java/couch/camping/domain/camplike/repository/CampLikeCustomRepository.java
  src/main/java/couch/camping/domain/camplike/repository/CampLikeCustomRepositoryImpl.java
  src/main/java/couch/camping/domain/comment/repository/CommentCustomRepository.java
  src/main/java/couch/camping/domain/comment/repository/CommentCustomRepositoryImpl.java
  src/main/java/couch/camping/domain/comment/service/CommentService.java
  src/main/java/couch/camping/domain/comment/service/CommentServiceImpl.java
  src/main/java/couch/camping/domain/comment/service/CommentServiceLocalImpl.java
  src/main/java/couch/camping/domain/post/entity/Post.java
  src/main/java/couch/camping/domain/post/repository/PostCustomRepository.java
  src/main/java/couch/camping/domain/post/repository/PostCustomRepositoryImpl.java
  src/main/java/couch/camping/domain/post/service/PostService.java
  src/main/java/couch/camping/domain/post/service/PostServiceImpl.java
  src/main/java/couch/camping/domain/post/service/PostServiceLocalImpl.java
  src/test/java/couch/camping/domain/post/service/PostServiceLocalImplTest.java
Labels: master<-develop
